### ISSUE TITLE
Console does not outputs Lua `print`?

### ISSUE THREAD

**Issue by AxDSan** [niemand-sec/LuaHook#2]
Hi there,

Amazing project you have here! I would have never thought I could have ever gotten this far with the help of your project, I loved the read @ https://niemand.com.ar/2019/02/15/why-leveling-if-you-can-just-use-lua-hacking-lua-inside-games/ and totally enjoyed it, it was let me to actually implement this into another game and low and behold, it works like a charm, I had to make some changes, e.g. the Lua is embedded in my target so I had to remove all references when you get the lua51 module instead I had to manually find the function (gettop, settop, loadfile, etc., etc.) addresses and so on...

Now my thing is that I have been trying to understand how this works and this projects has broaden my very limited knowledge on hooking lua and working with it in general, my issue comes from trying to output the actual print from lua itself to the allocated console... however I haven't been able to accomplish this...

It just won't print... either `print("hello world")` nor `io.write("Hello world, from ",_VERSION,"!\n")`

So I'm actually writing all my output to a file, which is quite unconventional knowing I have `print` available but it does not works.

**Comment by niemand-sec** [comment]
Hi @AxDSan I'm happy to know that my blog post and repo helped you to push further your knowledge :D

It's been a while since I played with Lua, if I recall correctly the context where Lua is trying to `print` your information is not your console. Remember lua it self has it's own context, classes, methods, etc. And the print function will try to print things out on its console. What you could do it's to spawn the lua console and see if it is showing the info there.

**Comment by AxDSan** [comment]
> Hi @AxDSan I'm happy to know that my blog post and repo helped you to push further your knowledge :D
> 
> It's been a while since I played with Lua, if I recall correctly the context where Lua is trying to `print` your information is not your console. Remember lua it self has it's own context, classes, methods, etc. And the print function will try to print things out on its console. What you could do it's to spawn the lua console and see if it is showing the info there.

Hey @niemand-sec Thank you so much for replying! so there lies the issue! I was thinking in something like this, because the game have scripts (mainly UI) that are getting executed, and I have seen some `print()` commands and when I look at my hooked console, I obviously don't see anything, so now tying up everything together with what you've said then indeed it has to be on its own console.

Now the big question is... How do I actually spawn the Lua console? pardon my limited knowledge on this, if you have any reference or post where I could read more on this, or if you would like to share the knowledge yourself, I will greatly appreciate it. Or is it something I should reverse into the game?

**Comment by niemand-sec** [comment]
I don't have any useful post in my notes atm. But if anything comes to my mind I will let you know. Depending on the game you will already have a console there, you just need to find it an enable it. If not you can enable it by your own (I'm pretty sure you will find info about that on internet). Another option is to create it by yourself with ImGui and invoking the proper methods.

**Comment by AxDSan** [comment]
> I don't have any useful post in my notes atm. But if anything comes to my mind I will let you know. Depending on the game you will already have a console there, you just need to find it an enable it. If not you can enable it by your own (I'm pretty sure you will find info about that on internet). Another option is to create it by yourself with ImGui and invoking the proper methods.

Alright, thank you so much for the information with that it should get me started somewhere :D 🕺
